# Generated by Django 4.0a1 on 2021-11-09 15:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0005_alter_product_image'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={},
        ),
    ]
