# Generated by Django 4.0a1 on 2021-11-04 22:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='detsale',
            name='prod',
        ),
        migrations.RemoveField(
            model_name='detsale',
            name='sale',
        ),
        migrations.RemoveField(
            model_name='product',
            name='cat',
        ),
        migrations.RemoveField(
            model_name='sale',
            name='cli',
        ),
        migrations.DeleteModel(
            name='Category',
        ),
        migrations.DeleteModel(
            name='Client',
        ),
        migrations.DeleteModel(
            name='DetSale',
        ),
        migrations.DeleteModel(
            name='Product',
        ),
        migrations.DeleteModel(
            name='Sale',
        ),
    ]
